name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for ${{ matrix.build.name }}
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        build:
          - { os: linux, arch: 386, name: linux-386, zig: x86-linux }
          - { os: linux, arch: amd64, name: linux-amd64, zig: x86_64-linux }
          - { os: linux, arch: arm, name: linux-arm, zig: arm-linux-musleabihf }
          - { os: linux, arch: arm64, name: linux-arm64, zig: aarch64-linux }
          - { os: linux, arch: riscv64, name: linux-riscv64, zig: riscv64-linux }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Build for ${{ matrix.build.name }}
        run: |
          VERSION=$(git describe --always --tags --match "v*" --dirty="-dev")
          CC="zig cc -target ${{ matrix.build.zig }}" CGO_ENABLED=1 GOOS=${{ matrix.build.os }} GOARCH=${{ matrix.build.arch }} go build -trimpath -ldflags="-w -s -X main.Version=${VERSION}" -o estkme-cloud-${{ matrix.build.name }}

      - name: Upload ${{ matrix.build.name }} to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: estkme-cloud-${{ matrix.build.name }}
          path: estkme-cloud-${{ matrix.build.name }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*"
