name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for ${{ matrix.target.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - { os: linux, arch: amd64, name: Linux AMD64 }
          - { os: linux, arch: arm64, name: Linux ARM64 }
          - { os: darwin, arch: amd64, name: macOS AMD64 }
          - { os: darwin, arch: arm64, name: macOS ARM64 }
          - { os: windows, arch: amd64, name: Windows AMD64 }
          - { os: windows, arch: arm64, name: Windows ARM64 }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go
      - name: Build for ${{ matrix.target.name }}
        run: |
          VERSION=$(git describe --always --tags --match "v*" --dirty="-dev")
          CGO_ENABLED=0 GOOS=${{ matrix.target.os }} GOARCH=${{ matrix.target.arch }} go build -trimpath -ldflags="-w -s -X main.Version=${VERSION}" -o estkme-cloud-${{ matrix.target.os }}-${{ matrix.target.arch }}
      - name: Upload ${{ matrix.target.name }} to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: estkme-cloud-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: estkme-cloud-${{ matrix.target.os }}-${{ matrix.target.arch }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*"
