name: Deploy

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy the latest version
        env:
          SSH_SERVER_LIST: ${{ vars.SSH_SERVER_LIST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "SSH_PRIVATE_KEY is not set"
            exit 1
          fi

          if [ -z "$SSH_SERVER_LIST" ]; then
            echo "SSH_SERVER_LIST is not set"
            exit 1
          fi

          # Save the private key to a file
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519

          # Split SSH_SERVER_LIST by comma
          IFS=',' read -ra SERVER_LIST <<< "$SSH_SERVER_LIST"
          for server in "${SERVER_LIST[@]}"; do
            ssh -i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=no "$server" "mkdir -p /opt/estkme-cloud"
            scp -i $HOME/.ssh/id_ed25519 -r scripts/deploy.sh $server:/opt/estkme-cloud
            ssh -i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=no  $server "sudo /opt/estkme-cloud/deploy.sh && rm -f /opt/estkme-cloud/deploy.sh"
          done



