name: Deploy

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy the latest version
        env:
          SSH_SERVER_LIST: ${{ vars.SSH_SERVER_LIST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "SSH_PRIVATE_KEY is not set"
            exit 1
          fi
          echo "$SSH_PRIVATE_KEY"

          if [ -z "$SSH_SERVER_LIST" ]; then
            echo "SSH_SERVER_LIST is not set"
            exit 1
          fi

          # Split SSH_SERVER_LIST by comma
          IFS=',' read -ra SERVER_LIST <<< "$SSH_SERVER_LIST"
          for server in "${SERVER_LIST[@]}"; do
            echo "$SSH_PRIVATE_KEY" | ssh -i /dev/stdin -o StrictHostKeyChecking=no "$server" "mkdir -p /opt/estkme-cloud"
            echo "$SSH_PRIVATE_KEY" | scp -i /dev/stdin -r ./deploy.sh $server:/opt/estkme-cloud
            echo "$SSH_PRIVATE_KEY" | ssh -i /dev/stdin -o StrictHostKeyChecking=no  $server "/opt/estkme-cloud/deploy.sh && rm -f /opt/estkme-cloud/deploy.sh"
          done



