name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for ${{ matrix.build.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - { os: linux, arch: amd64, name: Linux amd64 }
          - { os: linux, arch: arm64, name: Linux arm64 }
          - { os: darwin, arch: amd64, name: macOS amd64 }
          - { os: windows, arch: amd64, name: Windows amd64 }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - name: Build for ${{ matrix.build.name }}
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -trimpath -ldflags="-w -s" -o estkme-rlpa-server-${{ matrix.os }}-${{ matrix.arch }}
          chmod +x estkme-rlpa-server-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload ${{ matrix.build.name }} to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: estkme-rlpa-server-${{ matrix.os }}-${{ matrix.arch }}
          path: estkme-rlpa-server-${{ matrix.os }}-${{ matrix.arch }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: '*'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          files: '*'
