name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
        id: go

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-w -s" -o estkme-rlpa-server-${{ matrix.goos }}-${{ matrix.goarch }}
          chmod +x estkme-rlpa-server-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: estkme-rlpa-server-${{ matrix.goos }}-${{ matrix.goarch }}
          path: estkme-rlpa-server-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: '*'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          files: '*'
