name: Tag and Build on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag-and-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag=$TAG_NAME" >> $GITHUB_ENV

      - name: Trigger build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          inputs: '{"tag": "${{ env.tag }}"}'
